[project]
name = "webhook-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Josh", email = "104656760+js-cohn@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=3.4.6",
    "httpx>=0.28.1",
]

[project.scripts]
webhook-mcp = "webhook_mcp:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
